seed: 7

dataset_name: wikitext-2
dataset_cache_dir: /mnt/data/enzeyu/hf_downloads/datasets
tokenizer_name: /mnt/data/enzeyu/hf_downloads/models/gpt2
hf_local_files_only: true

model_backend: mdlm
use_pretrained_edge: true
require_pretrained_edge: true
edge_model_name_or_path: /mnt/data/enzeyu/hf_downloads/models/mdlm-no_flashattn-fp32-owt
pretrained_edge_path: /mnt/data/enzeyu/hf_downloads/models/mdlm-no_flashattn-fp32-owt

device_model_type: gpt2_small
device_model_name_or_path: /mnt/data/enzeyu/hf_downloads/models/gpt2
assist_method: gpt2_candidate_rerank

uncertainty_score: entropy
hard_token_ratio: 0.3
device_top_k: 20
gpt2_assist_alpha: 0.5
gpt2_query_batch_size: 64

max_train_examples: 100000000
max_val_examples: 100000000
max_train_blocks: 100000000
max_val_blocks: 100000000
num_workers: 2

max_length: 128
batch_size: 8
eval_steps: 200
eval_log_steps: 20
mask_ratio: 0.15

edge_model_name: mdlm-no_flashattn-fp32-owt
edge_hidden_size: auto
edge_layers: auto
edge_heads: auto

dropout: 0.1
precision: bf16

save_dir: results/wikitext2_mdlm_gpt2_assist
